server {
    listen 8080;
    server_name nguyen7-wa.dev.spsejecna.net;
    port_in_redirect off;
    # Hlavn   ko ^yenov   slo  ka
    root /var/www/html;
    index index.html index.php;

    client_max_body_size 512M;
    fastcgi_buffers 64 4K;

    # 1. Hlavn   str  nka (Dashboard)
    location / {
        try_files $uri $uri/ =404;
    }

    # 2. OwnCloud (v podslo  ce)
    location /owncloud {
        # Pokud soubor neexistuje, po  li to na index.php uvnit ^y owncloudu
        try_files $uri /owncloud/index.php$request_uri;
    }

    # Pravidlo pro m  j HTML web
    location /chat {
    alias /var/www/html/chat;
    index chat.html;
try_files $uri $uri/ =404;
    }

    # Zabezpe ^men   slo  ek OwnCloudu
    location ~ ^/owncloud/(?:build|tests|config|lib|3rdparty|templates|data)/ {
        deny all;
    }

    # 3. Zpracov  n   PHP (Univerz  ln  )
    location ~ \.php(?:$|/) {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        include fastcgi_params;

        # Tady je kouzlo - jednoduch   cesta
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_param HTTPS off;
        fastcgi_param HTTP_AUTHORIZATION $http_authorization;
        fastcgi_param modHeadersAvailable true;
        fastcgi_param front_controller_active true;

        fastcgi_pass unix:/run/php/php7.4-fpm.sock;
        fastcgi_intercept_errors on;
        fastcgi_request_buffering off;
    }
}
